version: '2'

services:
  resume:
    build: images/resume
    image: resume
    networks: 
      - jameslind_info_net
    ports:
      - 8080:8080
    volumes:
      - $RESUME_PATH:/go/src/app/resume.md

networks:
  jameslind_info_net: