version: '2'

services:
  resume:
    build: images/resume
    image: resume
    networks:
      - jameslind_info_net
    ports:
      - 8080:8080
    volumes:
      - ./resume.md:/go/src/app/resume.md
    environment: 
      - VIRTUAL_HOST=$RESUME_VHOST.$DOMAIN

networks:
  jameslind_info_net:
    # external: 
    #   name: wpwarpaints_net