version: '3.4'

services:
  resume:
    build:
      context: ./
    image: jlind/resume
    networks:
      - net
    volumes:
      - ./resume/web/:/usr/share/resume/
    environment: 
      - VIRTUAL_HOST=$RESUME_VHOST.$DOMAIN
    working_dir: /usr/share/resume/

networks:
  net:
    external: 
      name: docker-reverse-proxy_net