version: '3.4'

services:
  resume:
    build:
      context: ./
    image: jlind/resume
    networks:
      - net
    volumes:
      - ./resume/:/go/src/github.com/byteporter/resume/
    environment: 
      - VIRTUAL_HOST=$RESUME_VHOST.$DOMAIN
    working_dir: /go/src/github.com/byteporter/resume/
    expose:
      - 80
    ports:
      - 8080:80

networks:
  net:
    external: 
      name: infrastructure_net