version: '3.4'

services:
  resume:
    build: images/resume
    image: resume
    networks:
      - net
    volumes:
      - ./images/resume/app/resume.md:/go/src/app/resume.md
    environment: 
      - VIRTUAL_HOST=$RESUME_VHOST.$DOMAIN
      - LETSENCRYPT_HOST=$DOMAIN,$RESUME_VHOST.$DOMAIN
      - LETSENCRYPT_EMAIL=$WEBMASTER_EMAIL

networks:
  net:
    external: 
      name: infrastructure_net