version: '2'

services:
  resume:
    build: images/resume
    image: resume
    networks:
      - net
    volumes:
      - ./images/resume/app/resume.md:/go/src/app/resume.md
    environment: 
      - VIRTUAL_HOST=$RESUME_VHOST.$DOMAIN

networks:
  net:
    external: 
      name: infrastructure_net