version: '3.4'

services:
  resume:
    image: golang:latest
    networks:
      - net
    volumes:
      - ./resume/:/go/src/github.com/byteporter/resume/
      - resume_store:/go/
      - ./build-resume.sh:/usr/bin/build-resume:ro
    environment: 
      - VIRTUAL_HOST=$RESUME_VHOST.$DOMAIN
    working_dir: /go/src/github.com/byteporter/resume/
    expose:
      - 80
    command: ["build-resume"]

volumes:
  resume_store:

networks:
  net:
    external: 
      name: infrastructure_net